--application
CREATE TABLE IF NOT EXISTS "application"();
ALTER TABLE "application" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "application" ADD COLUMN IF NOT EXISTS "name" VARCHAR(15);

--bank
CREATE TABLE IF NOT EXISTS "bank"();
ALTER TABLE "bank" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "bank" ADD COLUMN IF NOT EXISTS "name" VARCHAR(50);
ALTER TABLE "bank" ADD COLUMN IF NOT EXISTS "image" VARCHAR(200);

--bankAccount
CREATE TABLE IF NOT EXISTS "bankAccount"();
ALTER TABLE "bankAccount" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "bankAccount" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "bankAccount" ADD COLUMN IF NOT EXISTS "name" VARCHAR(30);
ALTER TABLE "bankAccount" ADD COLUMN IF NOT EXISTS "bankId" UUID;
ALTER TABLE "bankAccount" ADD COLUMN IF NOT EXISTS "agency" VARCHAR(4);
ALTER TABLE "bankAccount" ADD COLUMN IF NOT EXISTS "agencyDigit" VARCHAR(1);
ALTER TABLE "bankAccount" ADD COLUMN IF NOT EXISTS "account" VARCHAR(10);
ALTER TABLE "bankAccount" ADD COLUMN IF NOT EXISTS "accountDigit" VARCHAR(1);
ALTER TABLE "bankAccount" ADD COLUMN IF NOT EXISTS "integrationId" UUID;

--bankAccountStatement
CREATE TABLE IF NOT EXISTS "bankAccountStatement"();
ALTER TABLE "bankAccountStatement" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "bankAccountStatement" ADD COLUMN IF NOT EXISTS "entryAt" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "bankAccountStatement" ADD COLUMN IF NOT EXISTS "partnerId" UUID;
ALTER TABLE "bankAccountStatement" ADD COLUMN IF NOT EXISTS "bankAccountId" UUID;
ALTER TABLE "bankAccountStatement" ADD COLUMN IF NOT EXISTS "currencyMethodId" UUID;
ALTER TABLE "bankAccountStatement" ADD COLUMN IF NOT EXISTS "categorieId" UUID;
ALTER TABLE "bankAccountStatement" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(18, 2);

--cashier
CREATE TABLE IF NOT EXISTS "cashier"();
ALTER TABLE "cashier" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "cashier" ADD COLUMN IF NOT EXISTS "date" TIMESTAMPTZ;
ALTER TABLE "cashier" ADD COLUMN IF NOT EXISTS "bankAccountId" UUID;
ALTER TABLE "cashier" ADD COLUMN IF NOT EXISTS "categorieId" UUID;
ALTER TABLE "cashier" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(18, 2);

--company
CREATE TABLE IF NOT EXISTS "company"();
ALTER TABLE "company" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "company" ADD COLUMN IF NOT EXISTS "name" VARCHAR(100);
ALTER TABLE "company" ADD COLUMN IF NOT EXISTS "surname" VARCHAR(80);

--companyIntegration
CREATE TABLE IF NOT EXISTS "companyIntegration"();
ALTER TABLE "companyIntegration" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "companyIntegration" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "companyIntegration" ADD COLUMN IF NOT EXISTS "integrationId" UUID;
ALTER TABLE "companyIntegration" ADD COLUMN IF NOT EXISTS "options" JSON;

--companyRole
CREATE TABLE IF NOT EXISTS "companyRole"();
ALTER TABLE "companyRole" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "companyRole" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "companyRole" ADD COLUMN IF NOT EXISTS "roleId" UUID;

--companyUser
CREATE TABLE IF NOT EXISTS "companyUser"();
ALTER TABLE "companyUser" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "companyUser" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "companyUser" ADD COLUMN IF NOT EXISTS "userId" UUID;
ALTER TABLE "companyUser" ADD COLUMN IF NOT EXISTS "roleId" UUID;

--contabilityCategorie
CREATE TABLE IF NOT EXISTS "contabilityCategorie"();
ALTER TABLE "contabilityCategorie" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "contabilityCategorie" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "contabilityCategorie" ADD COLUMN IF NOT EXISTS "name" VARCHAR(50);

--cte
CREATE TABLE IF NOT EXISTS "cte"();
ALTER TABLE "cte" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "cte" ADD COLUMN IF NOT EXISTS "cte" JSON;

--currencyMethod
CREATE TABLE IF NOT EXISTS "currencyMethod"();
ALTER TABLE "currencyMethod" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "currencyMethod" ADD COLUMN IF NOT EXISTS "name" VARCHAR(50);

--integration
CREATE TABLE IF NOT EXISTS "integration"();
ALTER TABLE "integration" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "integration" ADD COLUMN IF NOT EXISTS "name" VARCHAR(50);
ALTER TABLE "integration" ADD COLUMN IF NOT EXISTS "image" VARCHAR(200);

--integrationSSW
CREATE TABLE IF NOT EXISTS "integrationSSW"();
ALTER TABLE "integrationSSW" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "integrationSSW" ADD COLUMN IF NOT EXISTS "code" VARCHAR(10);

--partner
CREATE TABLE IF NOT EXISTS "partner"();
ALTER TABLE "partner" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "partner" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "partner" ADD COLUMN IF NOT EXISTS "name" VARCHAR(100);
ALTER TABLE "partner" ADD COLUMN IF NOT EXISTS "surname" VARCHAR(100);

--payment
CREATE TABLE IF NOT EXISTS "payment"();
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "documentNumber" VARCHAR(15);
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "currencyMethoId" UUID;
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "issueDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "partnerId" UUID;
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "bankAccountId" UUID;
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "categorieId" UUID;
ALTER TABLE "payment" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(18, 2);

--paymentMethod
CREATE TABLE IF NOT EXISTS "paymentMethod"();
ALTER TABLE "paymentMethod" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "paymentMethod" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "paymentMethod" ADD COLUMN IF NOT EXISTS "currencyMethodId" UUID;

--product
CREATE TABLE IF NOT EXISTS "product"();
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "name" VARCHAR(100);
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "inactivatedAt" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "situation" VARCHAR GENERATED ALWAYS AS (CASE WHEN "deletedAt" IS NOT NULL THEN 'deleted' WHEN "inactivatedAt" IS NOT NULL THEN 'inactive' ELSE 'active' END) STORED;

--receivement
CREATE TABLE IF NOT EXISTS "receivement"();
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "documentNumber" VARCHAR(15);
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "currencyMethoId" UUID;
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "issueDate" TIMESTAMP WITHOUT TIME;
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP WITHOUT TIME;
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "partnerId" UUID;
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "bankAccountId" UUID;
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "categorieId" UUID;
ALTER TABLE "receivement" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(18, 2);

--receivementMethod
CREATE TABLE IF NOT EXISTS "receivementMethod"();
ALTER TABLE "receivementMethod" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "receivementMethod" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "receivementMethod" ADD COLUMN IF NOT EXISTS "currencyMethodId" UUID;

--session
CREATE TABLE IF NOT EXISTS "session"();
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "userId" UUID;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "lastAcess" TIMESTAMPTZ;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "expireIn" SMALLINT;

--role
CREATE TABLE IF NOT EXISTS "role"();
ALTER TABLE "role" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "role" ADD COLUMN IF NOT EXISTS "name" VARCHAR(30);

--roleRule
CREATE TABLE IF NOT EXISTS "roleRule"();
ALTER TABLE "roleRule" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "roleRule" ADD COLUMN IF NOT EXISTS "roleId" UUID;
ALTER TABLE "roleRule" ADD COLUMN IF NOT EXISTS "ruleId" UUID;

--rule
CREATE TABLE IF NOT EXISTS "rule"();
ALTER TABLE "rule" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "rule" ADD COLUMN IF NOT EXISTS "description" VARCHAR(100);

--statement
CREATE TABLE IF NOT EXISTS "statement"();
ALTER TABLE "statement" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "statement" ADD COLUMN IF NOT EXISTS "bankAccountId" UUID;
ALTER TABLE "statement" ADD COLUMN IF NOT EXISTS "sourceId" VARCHAR(30);
ALTER TABLE "statement" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ;
ALTER TABLE "statement" ADD COLUMN IF NOT EXISTS "begin" TIMESTAMPTZ;
ALTER TABLE "statement" ADD COLUMN IF NOT EXISTS "end" TIMESTAMPTZ;
ALTER TABLE "statement" ADD COLUMN IF NOT EXISTS "conciledAt" TIMESTAMPTZ;

--task
CREATE TABLE IF NOT EXISTS "task"();
ALTER TABLE "task" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "task" ADD COLUMN IF NOT EXISTS "companyId" UUID;
ALTER TABLE "task" ADD COLUMN IF NOT EXISTS "schedule" VARCHAR(20);
ALTER TABLE "task" ADD COLUMN IF NOT EXISTS "methodId" UUID;
ALTER TABLE "task" ADD COLUMN IF NOT EXISTS "arguments" JSON;
ALTER TABLE "task" ADD COLUMN IF NOT EXISTS "inactivatedAt" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "task" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "task" ADD COLUMN IF NOT EXISTS "status" VARCHAR GENERATED ALWAYS AS (CASE WHEN "deletedAt" IS NOT NULL THEN 'deleted' WHEN "inactivatedAt" IS NOT NULL THEN 'inactived' ELSE 'active' END) STORED;

--taskHistory
CREATE TABLE IF NOT EXISTS "taskHistory"();
ALTER TABLE "taskHistory" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "taskHistory" ADD COLUMN IF NOT EXISTS "entryAt" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "taskHistory" ADD COLUMN IF NOT EXISTS "taskId" UUID;
ALTER TABLE "taskHistory" ADD COLUMN IF NOT EXISTS "finishedAt" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "taskHistory" ADD COLUMN IF NOT EXISTS "error" VARCHAR(200);

--taskMethod
CREATE TABLE IF NOT EXISTS "taskMethod"();
ALTER TABLE "taskMethod" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "taskMethod" ADD COLUMN IF NOT EXISTS "name" VARCHAR(30);

--user
CREATE TABLE IF NOT EXISTS "user"();
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "name" VARCHAR(100);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "email" VARCHAR(80);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "password" VARCHAR(15);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "inactivatedAt" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "status" VARCHAR GENERATED ALWAYS AS (CASE WHEN "deletedAt" IS NOT NULL THEN 'deleted' WHEN "inactivatedAt" IS NOT NULL THEN 'inactived' ELSE 'active' END) STORED;
